name: DebugBuild
on:
  push:
    branches:
      - master
env:
  #リポジトリのルートディレクトリを基点としたソリューションファイルのパス
  SOLUTION_FILE_PATH: project/GE3.sln
  #Visual Studio　の構成(Debug / Release)
  CONFIGRATION: Debug
jobs:
  build:
    runs_on: windows-2022

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Add MSBuild to Path
        uses: microsoft/setup-msbuild@v2
        with: 
          msbuild-architecture: x64
      - name: Build
        run:
          msbuild ${{env.SOLUTION_FILE_PATH}} / p:Platform=x64,Configuratoin=${{env.CONFIGRATION}}
